import { UGNextIssueModel } from './../network/Model/LottoGamesModel';
import AppDefine from "../define/AppDefine";
import {useEffect, useState} from "react";
import APIRouter from "../network/APIRouter";

export const getGameList = (data: UGNextIssueModel[]) => {
    console.log(AppDefine.siteId)
    let games = []
    if (data)
        games = data
    if (AppDefine.siteId == 'c085_2') {   //c085_2
        games = [
            {
                "id": 70,
                "changlong": false,
                "title": "香港六合彩",
                "name": "lhc",
                "sort": 1,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "1",
                "gameType": "lhc",
                "is_own": 0
            },
            {
                "id": 218,
                "changlong": false,
                "title": "新加坡六合彩",
                "name": "xjplhc68",
                "sort": 0,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "70",
                "isInstant": "0",
                "lowFreq": "1",
                "gameType": "lhc",
                "is_own": 1
            },
            {
                "id": 182,
                "changlong": false,
                "title": "新加坡5分六合彩",
                "name": "xjp5flhc",
                "sort": 2,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "70",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "lhc",
                "is_own": 1
            },
            {
                "id": 202,
                "changlong": false,
                "title": "菲律宾3分飞艇",
                "name": "ft",
                "sort": 3,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "55",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "xyft",
                "is_own": 1
            },
            {
                "id": 191,
                "changlong": false,
                "title": "菲律宾1分飞艇",
                "name": "flb1fft",
                "sort": 5,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "55",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "xyft",
                "is_own": 1
            },
            {
                "id": 181,
                "changlong": false,
                "title": "新加坡1分六合彩",
                "name": "fflhc",
                "sort": 4,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "70",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "lhc",
                "is_own": 1
            },
            {
                "id": 170,
                "changlong": false,
                "title": "极速赛车",
                "name": "jssc",
                "sort": 6,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 193,
                "changlong": false,
                "title": "菲律宾1分赛车",
                "name": "flb1fsc",
                "sort": 10,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 165,
                "changlong": false,
                "title": "极速六合彩",
                "name": "jslhc",
                "sort": 28,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "70",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "lhc",
                "is_own": 1
            },
            {
                "id": 50,
                "changlong": false,
                "title": "北京赛车(PK10)",
                "name": "pk10",
                "sort": 11,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 0
            },
            {
                "id": 223,
                "changlong": false,
                "title": "幸运赛马",
                "name": "xysm",
                "sort": 59,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 220,
                "changlong": false,
                "title": "极速赛马",
                "name": "jssm",
                "sort": 58,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 1,
                "changlong": false,
                "title": "重庆时时彩",
                "name": "cqssc",
                "sort": 11,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 0
            },
            {
                "id": 55,
                "changlong": false,
                "title": "幸运飞艇",
                "name": "xyft",
                "sort": 11,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "xyft",
                "is_own": 0
            },
            {
                "id": 166,
                "changlong": false,
                "title": "极速飞艇",
                "name": "jsft",
                "sort": 9,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "55",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "xyft",
                "is_own": 1
            },
            {
                "id": 180,
                "changlong": false,
                "title": "腾讯分分彩",
                "name": "txffc",
                "sort": 26,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "1",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 1
            },
            {
                "id": 164,
                "changlong": false,
                "title": "极速时时彩",
                "name": "jsssc",
                "sort": 9,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "1",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 1
            },
            {
                "id": 172,
                "changlong": false,
                "title": "幸运赛车",
                "name": "xysc",
                "sort": 35,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 168,
                "changlong": false,
                "title": "极速快三",
                "name": "jssb",
                "sort": 8,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "10",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "jsk3",
                "is_own": 1
            },
            {
                "id": 197,
                "changlong": false,
                "title": "菲律宾5分赛车",
                "name": "flbwfsc",
                "sort": 10,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 200,
                "changlong": false,
                "title": "极速3D",
                "name": "js3dd",
                "sort": 42,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "6",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "fc3d",
                "is_own": 1
            },
            {
                "id": 6,
                "changlong": false,
                "title": "福彩3D",
                "name": "fc3d",
                "sort": 18,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "1",
                "gameType": "fc3d",
                "is_own": 0
            },
            {
                "id": 194,
                "changlong": false,
                "title": "菲律宾5分时时彩",
                "name": "flb5fssc",
                "sort": 7,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "1",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 1
            },
            {
                "id": 195,
                "changlong": false,
                "title": "菲律宾1分时时彩",
                "name": "flb1fssc",
                "sort": 11,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "1",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 1
            },
            {
                "id": 169,
                "changlong": false,
                "title": "极速11选5",
                "name": "jssyxw",
                "sort": 32,
                "cate": 2,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "21",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "gd11x5",
                "is_own": 1
            },
            {
                "id": 21,
                "changlong": false,
                "title": "广东11选5",
                "name": "gd11x5",
                "sort": 23,
                "cate": 2,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "gd11x5",
                "is_own": 0
            },

            {
                "id": 4,
                "changlong": false,
                "title": "UG棋牌",
                "name": "ugcs",
                "sort": 0,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "ugcs",
                "is_own": 0
            }, {
                "id": 5,
                "changlong": false,
                "title": "开心棋牌",
                "name": "kxcs",
                "sort": 0,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "kxcs",
                "is_own": 0
            }, {
                "id": 198,
                "changlong": false,
                "title": "5分快三",
                "name": "wfks",
                "sort": 11,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "10",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "jsk3",
                "is_own": 1
            }, {
                "id": 3,
                "changlong": false,
                "title": "PK10牛牛",
                "name": "pk10nn",
                "sort": 12,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10nn",
                "is_own": 0
            }, {
                "id": 66,
                "changlong": false,
                "title": "PC蛋蛋",
                "name": "pcdd",
                "sort": 14,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pcdd",
                "is_own": 0
            }, {
                "id": 188,
                "changlong": false,
                "title": "北京快三",
                "name": "bjks",
                "sort": 15,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "10",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "jsk3",
                "is_own": 1
            }, {
                "id": 175,
                "changlong": false,
                "title": "北京28",
                "name": "beijing28",
                "sort": 16,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "66",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pcdd",
                "is_own": 1
            }, {
                "id": 171,
                "changlong": false,
                "title": "湖北快3",
                "name": "ofclhubk3",
                "sort": 19,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "10",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "jsk3",
                "is_own": 0
            }, {
                "id": 2,
                "changlong": false,
                "title": "七星彩",
                "name": "qxc",
                "sort": 20,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "1",
                "gameType": "qxc",
                "is_own": 0
            }, {
                "id": 187,
                "changlong": false,
                "title": "贵州快3",
                "name": "ofclgzk3",
                "sort": 21,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "10",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "jsk3",
                "is_own": 0,
                "adLink": "198",
                "adImage": "https://cdn01.yingao-xu.cn/upload/c085/customise/images/lottery_ad_187.jpg"
            }, {
                "id": 65,
                "changlong": false,
                "title": "北京快乐8",
                "name": "bjkl8",
                "sort": 24,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "bjkl8",
                "is_own": 0
            }, {
                "id": 178,
                "changlong": false,
                "title": "北京11选5",
                "name": "ofclbj11x5",
                "sort": 25,
                "cate": 2,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "21",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "gd11x5",
                "is_own": 0
            }, {
                "id": 179,
                "changlong": false,
                "title": "广西11选5",
                "name": "ofclgx11x5",
                "sort": 27,
                "cate": 2,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "21",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "gd11x5",
                "is_own": 0
            }, {
                "id": 167,
                "changlong": false,
                "title": "极速牛牛",
                "name": "jsnn",
                "sort": 31,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "3",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10nn",
                "is_own": 1
            }, {
                "id": 183,
                "changlong": false,
                "title": "分分3D",
                "name": "ff3d",
                "sort": 37,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "6",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "fc3d",
                "is_own": 1
            }, {
                "id": 184,
                "changlong": false,
                "title": "十分3D",
                "name": "sf3d",
                "sort": 38,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "6",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "fc3d",
                "is_own": 1
            }, {
                "id": 174,
                "changlong": false,
                "title": "极速快乐8",
                "name": "bj28",
                "sort": 40,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "65",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "bjkl8",
                "is_own": 1
            }, {
                "id": 173,
                "changlong": false,
                "title": "极速广东快乐十分",
                "name": "jsgdklsf",
                "sort": 41,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "60",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "gdkl10",
                "is_own": 1
            }, {
                "id": 7,
                "changlong": false,
                "title": "秒秒彩",
                "name": "ofclmmc",
                "sort": 45,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "1",
                "isInstant": "1",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 0
            }, {
                "id": 9,
                "changlong": false,
                "title": "赛车秒秒彩",
                "name": "pk10mmc",
                "sort": 45,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "50",
                "isInstant": "1",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 0
            }, {
                "id": 11,
                "changlong": false,
                "title": "六合秒秒彩",
                "name": "lhcmmc",
                "sort": 45,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "70",
                "isInstant": "1",
                "lowFreq": "0",
                "gameType": "lhc",
                "is_own": 0
            }, {
                "id": 12,
                "changlong": false,
                "title": "大乐透",
                "name": "dlt",
                "sort": 46,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "1",
                "gameType": "dlt",
                "is_own": 0
            }, {
                "id": 61,
                "changlong": false,
                "title": "重庆幸运农场",
                "name": "xync",
                "sort": 46,
                "cate": 4,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "xync",
                "is_own": 0
            }, {
                "id": 189,
                "changlong": false,
                "title": "分分幸运农场",
                "name": "ffxync",
                "sort": 47,
                "cate": 4,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "61",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "xync",
                "is_own": 1
            }, {
                "id": 219,
                "changlong": false,
                "title": "台湾六合彩",
                "name": "twlhc1",
                "sort": 58,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "70",
                "isInstant": "0",
                "lowFreq": "1",
                "gameType": "lhc",
                "is_own": 1
            }];
    }

    if (AppDefine.siteId == 'c085_3') {   //c085_3
        games = [
            {
                "id": 70,
                "changlong": false,
                "title": "香港六合彩",
                "name": "lhc",
                "sort": 1,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "1",
                "gameType": "lhc",
                "is_own": 0
            },
            {
                "id": 218,
                "changlong": false,
                "title": "新加坡六合彩",
                "name": "xjplhc68",
                "sort": 0,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "70",
                "isInstant": "0",
                "lowFreq": "1",
                "gameType": "lhc",
                "is_own": 1
            },
            {
                "id": 182,
                "changlong": false,
                "title": "新加坡5分六合彩",
                "name": "xjp5flhc",
                "sort": 2,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "70",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "lhc",
                "is_own": 1
            },
            {
                "id": 181,
                "changlong": false,
                "title": "新加坡1分六合彩",
                "name": "fflhc",
                "sort": 4,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "70",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "lhc",
                "is_own": 1
            },
            {
                "id": 202,
                "changlong": false,
                "title": "菲律宾3分飞艇",
                "name": "ft",
                "sort": 3,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "55",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "xyft",
                "is_own": 1
            },
            {
                "id": 191,
                "changlong": false,
                "title": "菲律宾1分飞艇",
                "name": "flb1fft",
                "sort": 5,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "55",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "xyft",
                "is_own": 1
            },
            {
                "id": 226,
                "changlong": false,
                "title": "幸运PK10赛车",
                "name": "xypk10sc",
                "sort": 9,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 170,
                "changlong": false,
                "title": "极速赛车",
                "name": "jssc",
                "sort": 6,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 223,
                "changlong": false,
                "title": "幸运赛马",
                "name": "xysm",
                "sort": 59,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 220,
                "changlong": false,
                "title": "极速赛马",
                "name": "jssm",
                "sort": 58,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 55,
                "changlong": false,
                "title": "幸运飞艇",
                "name": "xyft",
                "sort": 11,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "xyft",
                "is_own": 0
            },
            {
                "id": 166,
                "changlong": false,
                "title": "极速飞艇",
                "name": "jsft",
                "sort": 9,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "55",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "xyft",
                "is_own": 1
            },
            {
                "id": 222,
                "changlong": false,
                "title": "幸运时时彩",
                "name": "xyssc01",
                "sort": 15,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "1",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 1
            },
            {
                "id": 164,
                "changlong": false,
                "title": "极速时时彩",
                "name": "jsssc",
                "sort": 9,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "1",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 1
            },
            {
                "id": 225,
                "changlong": false,
                "title": "幸运六合彩",
                "name": "xylhc",
                "sort": 7,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "70",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "lhc",
                "is_own": 1
            },
            {
                "id": 165,
                "changlong": false,
                "title": "极速六合彩",
                "name": "jslhc",
                "sort": 28,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "70",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "lhc",
                "is_own": 1
            },
            {
                "id": 201,
                "changlong": false,
                "title": "幸运快三",
                "name": "xyk3",
                "sort": 17,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "10",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "jsk3",
                "is_own": 0
            },
            {
                "id": 168,
                "changlong": false,
                "title": "极速快三",
                "name": "jssb",
                "sort": 18,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "10",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "jsk3",
                "is_own": 0
            },
            {
                "id": 224,
                "changlong": false,
                "title": "幸运3D",
                "name": "xy3d",
                "sort": 24,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "6",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "fc3d",
                "is_own": 1
            },
            {
                "id": 200,
                "changlong": false,
                "title": "极速3D",
                "name": "js3dd",
                "sort": 42,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "6",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "fc3d",
                "is_own": 1
            },
            {
                "id": 172,
                "changlong": false,
                "title": "幸运赛车",
                "name": "xysc",
                "sort": 35,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 50,
                "changlong": false,
                "title": "北京赛车(PK10)",
                "name": "pk10",
                "sort": 11,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 0
            },
            {
                "id": 180,
                "changlong": false,
                "title": "腾讯分分彩",
                "name": "txffc",
                "sort": 26,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "1",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 1
            },
            {
                "id": 1,
                "changlong": false,
                "title": "重庆时时彩",
                "name": "cqssc",
                "sort": 11,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 0
            },
            {
                "id": 6,
                "changlong": false,
                "title": "福彩3D",
                "name": "fc3d",
                "sort": 18,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "1",
                "gameType": "fc3d",
                "is_own": 0
            },
            {
                "id": 66,
                "changlong": false,
                "title": "PC蛋蛋",
                "name": "pcdd",
                "sort": 14,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pcdd",
                "is_own": 0
            },
            {
                "id": 197,
                "changlong": false,
                "title": "菲律宾5分赛车",
                "name": "flbwfsc",
                "sort": 10,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 193,
                "changlong": false,
                "title": "菲律宾1分赛车",
                "name": "flb1fsc",
                "sort": 10,
                "cate": 6,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "50",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "pk10",
                "is_own": 1
            },
            {
                "id": 194,
                "changlong": false,
                "title": "菲律宾5分时时彩",
                "name": "flb5fssc",
                "sort": 7,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "1",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 1
            },
            {
                "id": 195,
                "changlong": false,
                "title": "菲律宾1分时时彩",
                "name": "flb1fssc",
                "sort": 11,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "1",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "cqssc",
                "is_own": 1
            },
            {
                "id": 21,
                "changlong": false,
                "title": "广东11选5",
                "name": "gd11x5",
                "sort": 23,
                "cate": 2,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "gd11x5",
                "is_own": 0
            },
            {
                "id": 169,
                "changlong": false,
                "title": "极速11选5",
                "name": "jssyxw",
                "sort": 32,
                "cate": 2,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "21",
                "isInstant": "0",
                "lowFreq": "0",
                "gameType": "gd11x5",
                "is_own": 1
            },
            {
                "id": 12,
                "changlong": false,
                "title": "大乐透",
                "name": "dlt",
                "sort": 46,
                "cate": 1,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "0",
                "from_type": "0",
                "isInstant": "0",
                "lowFreq": "1",
                "gameType": "dlt",
                "is_own": 0
            },
            {
                "id": 219,
                "changlong": false,
                "title": "台湾六合彩",
                "name": "twlhc1",
                "sort": 58,
                "cate": 30,
                "open": 0,
                "enable": "1",
                "isSeal": "0",
                "customise": "2",
                "from_type": "70",
                "isInstant": "0",
                "lowFreq": "1",
                "gameType": "lhc",
                "is_own": 1
            }];
    }

    let trendGameList: UGNextIssueModel[] = []
    if (AppDefine.siteId != 'c085_2' || AppDefine.siteId != 'c085_3') {
        for (let i = 0; i < games.length; i++) {
            debugger
            let element = games[i];
            if (element.gameType == 'pcdd' || element.gameType == 'cqssc' || element.gameType == 'qxc' || element.gameType == 'xyft' || element.gameType == 'pk10nn' || element.gameType == 'pk10' || element.gameType == 'gd11x5' || element.gameType == 'jsk3' || element.gameType == 'gdkl10' || element.gameType == 'xync') {
                let mmcIndex = element.name.indexOf("mmc");  //过滤秒秒彩
                if (mmcIndex == -1) {   //element.name != 'pk10mmc' && element.name != 'ofclmmc'
                    trendGameList.push(element);
                    //$scope.chooseTemplate += '<li data-name='+element.name+'>'+element.title+'</li>';
                }
            }
            //设置默认显示彩种：北京赛车(PK10)
            // if(param){
            //     if(element.name == param){
            //         currentGameId = element.id;
            //         $scope.defaultTrendGame = element;
            //     }
            // }
        }
         // console.log("trendGameList", trendGameList)
    }

    if (AppDefine.siteId == 'c085_2') {
        for (let i = 0; i < games.length; i++) {
            let element = games[i];
            let mmcIndex = element.name.indexOf("mmc");  //过滤秒秒彩
            if (mmcIndex == -1) {   //element.name != 'pk10mmc' && element.name != 'ofclmmc'
                trendGameList.push(element);
            }
            // //设置默认显示彩种：北京赛车(PK10)
            // if(param){
            //     if(element.name == param){
            //         currentGameId = element.id;
            //         $scope.defaultTrendGame = element;
            //     }
            // }
        }

        let c085_2_GameList = [70, 218, 182, 202, 191, 181, 226, 170, 193, 225, 165, 50, 223, 220, 1, 55, 166, 180, 222, 164, 172, 201, 168, 197, 224, 200, 6, 194, 195, 169, 21, 12, 66, 219];
        let newList = [];
        let index, newIndex;
        for (index in games) {
            newIndex = c085_2_GameList.indexOf(games[index].id);
            if (newIndex > -1) {
                newList[newIndex] = games[index];
            }
        }
        let realList = [], i;
        for (i = 0; i < newList.length; i++) {
            if (typeof newList[i] != 'undefined') {
                realList.push(newList[i]);
            }
        }

        trendGameList = realList
        //
        // for(let i = 0; i < realList.length;i++){
        //     $scope.chooseTemplate = $scope.chooseTemplate+ '<li data-name='+games[i].name+'>'+ games[i].title+'</li>'
        // }

    }

    return trendGameList

    // $scope.chooseTemplate += '</ul>';
    // console.log($scope.trendGameList);
    // 渲染默认显示彩种走势
    // $scope.getLottoryDetail($scope.defaultTrendGame);

}
