import {UGThemeColor} from '../UGThemeColor';

// 简约
export const JYThemeColor: {[x: string]: UGThemeColor} = {
  //简约
  简约模板0: {
    skitType: '简约模板0',
    skitString: '简约模板 0蓝色',
    bgColor: ['#FFFFFF', '#FFFFFF'],
    navBarBgColor: ['#4463A5', '#4463A5'],
    tabBarBgColor: '#F4F4F4',
    tabNoSelectColor: '#525252',
    tabSelectedColor: '#010101',
    progressBgColor: ['#FEC434', '#FE8A23'],
    homeContentColor: '#FFFFFF',
    homeContentSubColor: '#D3D3D3',
    cellBgColor: '#FFFFFF',
    CLBgColor: '#E6E6E6',
    menuHeadViewColor: ['#fa7dc5', '#f5c3e0'],
    textColor1: '#111111',
    textColor2: '#555555',
    textColor3: '#C1C1C1',
    textColor4: '#FFFFFF',
    conversionCellColor: '#7BA2C2',
    intoViewColor: '#7BA2C2',
    moneyCellColor: '#9BB8CB',
  },
  简约模板1: {
    skitType: '简约模板1',
    skitString: '简约模板 1红色',
    bgColor: ['#FFFFFF', '#FFFFFF'],
    navBarBgColor: ['#fb8787', '#e45353'],
    tabBarBgColor: '#F4F4F4',
    tabNoSelectColor: '#525252',
    tabSelectedColor: '#010101',
    progressBgColor: ['#FEC434', '#FE8A23'],
    homeContentColor: '#FFFFFF',
    homeContentSubColor: '#D3D3D3',
    cellBgColor: '#FFFFFF',
    CLBgColor: '#E6E6E6',
    menuHeadViewColor: ['#fa7dc5', '#f5c3e0'],
    textColor1: '#111111',
    textColor2: '#555555',
    textColor3: '#C1C1C1',
    textColor4: '#FFFFFF',
    conversionCellColor: '#7BA2C2',
    intoViewColor: '#7BA2C2',
    moneyCellColor: '#9BB8CB',
  },
};
