export enum PageName {
  // ———————————— 通用页面 —————————————
  TransitionPage = 'TransitionPage',
  JDPromotionListPage = 'JDPromotionListPage',
  PromotionPage = 'PromotionPage',
  PromotionListPage = 'PromotionListPage',
  UpdateVersionPage = 'UpdateVersionPage',
  SeriesLobbyPage = 'SeriesLobbyPage',
  UserMessagePage = 'UserMessagePage',
  UserInfoPage = 'UserInfoPage',
  ActivityRewardPage = 'ActivityRewardPage',
  LotteryHistoryPage = 'LotteryHistoryPage',
  SafeCenterPage = 'SafeCenterPage',
  IncomeRecommendPage = 'IncomeRecommendPage',
  ManageBankListPage = 'ManageBankListPage',
  BetLotteryPage = 'BetLotteryPage',
  BtcPayPage = 'BtcPayPage',
  BtcTutorialPage = 'BtcTutorialPage',
  CapitalPage = 'CapitalPage',
  SetPasswordPage = 'SetPasswordPage',
  ForgetPasswordPage = 'ForgetPasswordPage',
  AddBankPage = 'AddBankPage',
  JDVirtualCurrencyTutorialPage = 'JDVirtualCurrencyTutorialPage',
  TrendView = 'TrendView',
  LottoSelector = 'LottoSelector',
  LottoBetting = 'LottoBetting',
  JDSigInPage = 'JDSigInPage',
  JDFeedBackPage = 'JDFeedBackPage',
  OnlinePayPage = 'OnlinePayPage',
  TransferPayPage = 'TransferPayPage',
  JDRedEnveloperPage = 'JDRedEnveloperPage',
  JDAgentPage = 'JDAgentPage',
  JDPromotionIncomePage = 'JDPromotionIncomePage',
  TaskCenterPage = 'TaskCenterPage',

  // ———————————— 模板页面 —————————————
  LHTHomePage = 'LHTHomePage',
  LHTPreferencePage = 'LHTPreferencePage',
  LHTMinePage = 'LHTMinePage',
  LHTSignInPage = 'LHTSignInPage',
  LHTSignUpPage = 'LHTSignUpPage',

  LCHomePage = 'LCHomePage',
  LCMinePage = 'LCMinePage',
  LCLoginPage = 'LCLoginPage',
  LCRegisterPage = 'LCRegisterPage',

  ZLHomePage = 'ZLHomePage',
  ZLLoginPage = 'ZLLoginPage',
  ZLMinePage = 'ZLMinePage',
  ZLRegisterPage = 'ZLRegisterPage',

  HJHomePage = 'HJHomePage',
  HJLoginPage = 'HJLoginPage',
  HJMinePage = 'HJMinePage',
  HJGameCategoryPage = 'HJGameCategoryPage',
  HJRegisterPage = 'HJRegisterPage',

  BZHHomePage = 'BZHHomePage',
  BZHMinePage = 'BZHMinePage',
  BZHSignInPage = 'BZHSignInPage',
  BZHSignUpPage = 'BZHSignUpPage',
  BZHGameLobbyPage = 'BZHGameLobbyPage',

  JXHHomePage = 'JXHHomePage',
  JXHMinePage = 'JXHMinePage',
  JXHSignInPage = 'JXHSignInPage',
  JXHSignUpPage = 'JXHSignUpPage',

  WNZHomePage = 'WNZHomePage',
  WNZMinePage = 'WNZMinePage',
  WNZSignUpPage = 'WNZSignUpPage',
  WNZSignInPage = 'WNZSignInPage',

  LLHomePage = 'LLHomePage',
  LLMinePage = 'LLMinePage',
  LLLoginPage = 'LLLoginPage',
  LLRegisterPage = 'LLRegisterPage',

  BYHomePage = 'BYHomePage',
  BYMinePage = 'BYMinePage',
  BYSignInPage = 'BYSignInPage',
  BYSignUpPage = 'BYSignUpPage',

  LEFHomePage = 'LEFHomePage',
  LEFMinePage = 'LEFMinePage',
  LEFSignInPage = 'LEFSignInPage',
  LEFSignUpPage = 'LEFSignUpPage',

  GameLobbyPage = 'GameLobbyPage',
  GameHallPage = 'GameHallPage',
  FreedomHallPage = 'FreedomHallPage',

  KSHomePage = 'KSHomePage',
  KSSignInPage = 'KSSignInPage',
  KSSignUpPage = 'KSSignUpPage',
  KSMinePage = 'KSMinePage',

  XBJLoginPage = 'XBJLoginPage',
  XBJRegisterPage = 'XBJRegisterPage',
  XBJMinePage = 'XBJMinePage',
  FeedbackRecordView = 'FeedbackRecordView',
  FeedbackSubmitView = 'FeedbackSubmitView',
  AlipayProfitView = 'AlipayProfitView',
  AlipayTransferRecordView = 'AlipayTransferRecordView',
  AlipayTransferView = 'AlipayTransferView',
  AlipayView = 'AlipayView',
  FeedbackView = 'FeedbackView',
  TransferRecordView = 'TransferRecordView',
  TransferTKLMainView = 'TransferTKLMainView',
  TransferView = 'TransferView',
  TransferLineView = 'TransferLineView',
  SupFeedbackSubmitView = 'SupFeedbackSubmitView',

  GDRegisterPage = 'GDRegisterPage',
  GDLoginPage = 'GDLoginPage',

  VietnamHome = 'VietnamHome',
  VietnamLogin = 'VietnamLogin',
  VietnamRegister = 'VietnamRegister',
  VietnamMine = 'VietnamMine',
  VietnamGameList = 'VietnamGameList',
  Game3rdView = "Game3rdView"
}
