export enum PageName {
  TransitionPage = 'TransitionPage',
  JDPromotionListPage = 'JDPromotionListPage', //优惠券列表
  LCHomePage = 'LCHomePage',
  LCMinePage = 'LCMinePage',
  LCTransferPage = 'LCTransferPage',
  LCPromotionsPage = 'LCPromotionsPage',
  LXBView = 'LXBView',
  UpdateVersionPage = 'UpdateVersionPage',
  ZHTYHomePage = 'ZHTYHomePage',
  ZHTYLoginPage = 'ZHTYLoginPage',
  ZHTYRegisterPage = 'ZHTYRegisterPage',
  ZHTYMinePage = 'ZHTYMinePage',
  LHTHomePage = 'LHTHomePage',
  LHTMinePage = 'LHTMinePage',
  LHTSignInPage = 'LHTSignInPage',
  LHTSignUpPage = 'LHTSignUpPage',
  ZLHomePage = 'ZLHomePage', //尊龙主页
  ZLLoginPage = 'ZLLoginPage', //尊龙登录
  ZLMinePage = 'ZLMinePage', //尊龙我的
  ZLRegisterPage = 'ZLRegisterPage', //尊龙注册
  HJHomePage = 'HJHomePage', //黑金主页
  HJLoginPage = 'HJLoginPage', //黑金登录
  HJMinePage = 'HJMinePage', //黑金我的
  HJGameCategoryPage = 'HJGameCategoryPage', //黑金分类条目
  HJRegisterPage = 'HJRegisterPage', //黑金注册
  BZHHomePage = 'BZHHomePage',
  BZHMinePage = 'BZHMinePage',
  BZHSignInPage = 'BZHSignInPage',
  BZHSignUpPage = 'BZHSignUpPage',
  BZHGameLobbyPage = 'BZHGameLobbyPage',
  JXHHomePage = 'JXHHomePage',
  JXHMinePage = 'JXHMinePage',
  JXHSignInPage = 'JXHSignInPage',
  JXHSignUpPage = 'JXHSignUpPage',
  GDRegisterPage = 'GDRegisterPage',
  GDLoginPage = 'GDLoginPage',
  WNZHomePage = 'WNZHomePage',
  WNZMinePage = 'WNZMinePage',
  WNZSignUpPage = 'WNZSignUpPage',
  WNZSignInPage = 'WNZSignInPage',
  WNZGameLobbyPage = 'WNZGameLobbyPage',
  PromotionListPage = 'PromotionListPage',
  LLHomePage = 'LLHomePage',
  LLMinePage = 'LLMinePage',
  LLLoginPage = 'LLLoginPage',
  LLRegisterPage = 'LLRegisterPage',
  BYHomePage = 'BYHomePage', //白曜
  BYMinePage = 'BYMinePage',
  BYSignInPage = 'BYSignInPage',
  BYSignUpPage = 'BYSignUpPage',
  LEFHomePage = 'LEFHomePage', //乐FUN
  LEFMinePage = 'LEFMinePage',
  LEFSignInPage = 'LEFSignInPage',
  LEFSignUpPage = 'LEFSignUpPage',
  KSHomePage = 'KSHomePage',
  KSSignInPage = 'KSSignInPage',
  KSSignUpPage = 'KSSignUpPage',
  KSMinePage = 'KSMinePage',
  LottoSelector = 'LottoSelector',
  LottoBetting = 'LottoBetting',
  VietnamHome = 'VietnamHome',
  VietnamLogin = 'VietnamLogin',
  VietnamRegister = 'VietnamRegister',
  VietnamMine = 'VietnamMine',
  VietnamGameList = 'VietnamGameList',
  LHTPreferencePage = 'LHTPreferencePage',
  TrendView = 'TrendView',
  JDVirtualCurrencyTutorialPage = 'JDVirtualCurrencyTutorialPage',
  LCLoginPage = 'LCLoginPage',
  LCRegisterPage = 'LCRegisterPage',
  PromotionPage = 'PromotionPage',
  XBJLoginPage = 'XBJLoginPage',
  XBJMinePage = 'XBJMinePage',
  XBJRegisterPage = 'XBJRegisterPage',
  TransferView = 'TransferView',
  TransferRecordView = 'TransferRecordView'
}
